In [6]:
import pandas as pd
import seaborn as sns

In [7]:
#attribute error: why does it occur?

data_ex1=pd.DataFrame({
    '학년':[2,3,4,1,1,2,2,3],
    '학교':['한양대','고려대','세종대','성균관대','연세대','서울대','경북대','부산대'],
    '전공':['체육교육과','수학교육과','국어교육과','컴퓨터공학과','전자공학과','신소재공학과','철학과','경영학과']
})

In [8]:
data_ex1

   학년    학교      전공
0   2   한양대   체육교육과
1   3   고려대   수학교육과
2   4   세종대   국어교육과
3   1  성균관대  컴퓨터공학과
4   1   연세대   전자공학과
5   2   서울대  신소재공학과
6   2   경북대     철학과
7   3   부산대    경영학과

In [9]:
#attribute error: why does it occur?
#sol: 'DataFrame'

data_ex2=pd.DataFrame({
    '학교':['한양대','고려대','세종대','성균관대','연세대','서울대','경북대','부산대'],
    '학년':[2,3,4,1,1,2,2,3],
    '나이':[21,22,27,20,19,23,24,22],
})

In [10]:
data_ex2

     학교  학년  나이
0   한양대   2  21
1   고려대   3  22
2   세종대   4  27
3  성균관대   1  20
4   연세대   1  19
5   서울대   2  23
6   경북대   2  24
7   부산대   3  22

In [11]:
tt=sns.load_dataset('titanic')

In [12]:
#셀을 순차적으로 실행해야 오류가 뜨지 않고 정상적으로 실행이 됨.

tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [13]:
tt[['age','embark_town','alive']]

      age  embark_town alive
0    22.0  Southampton    no
1    38.0    Cherbourg   yes
2    26.0  Southampton   yes
3    35.0  Southampton   yes
4    35.0  Southampton    no
..    ...          ...   ...
886  27.0  Southampton    no
887  19.0  Southampton   yes
888   NaN  Southampton    no
889  26.0    Cherbourg   yes
890  32.0   Queenstown    no

[891 rows x 3 columns]

In [14]:
#keyerror?
#using only one bracket for obtaining at least two columns -> error

tt['age','embark_town','alive']

KeyError: ('age', 'embark_town', 'alive')

In [ ]:
tt['age']

In [ ]:
type(tt)

In [ ]:
tt[['age']]*100

In [ ]:
#column(age) contains the value 'nan', then we have result 'nan'

sum(tt['age'])

In [ ]:
list(tt)

In [ ]:
type(list(tt))

In [ ]:
pd.Series(tt['age'])

In [ ]:
list(tt['age'])

In [ ]:
type(pd.Series(tt['age']))

In [ ]:
sum(tt['fare'])

In [ ]:
tt[['fare']]

In [ ]:
#mean value
sum(tt['fare'])/len(list(tt['age']))

In [ ]:
max(tt['age'])

In [ ]:
tt.head(10)

In [ ]:
#이것도 가능
tt['pclass'].head()

In [ ]:
tt[['pclass']].head()

In [ ]:
#(row, column)
tt.shape

In [ ]:
#int:정수형 데이터
#object:문자열, 객체형 데이터
#float:소수점 포함 연속형 데이터
#category:범주형 데이터
#bool:true/false
#dtype: object: 이 데이터 프레임의 자료형 정보가 object로 출력되었음을 의미

tt.dtypes

In [ ]:
tt.info()

In [ ]:
tt.describe()

In [ ]:
#Inverting integer types
tt.describe().astype(int)

In [ ]:
tt.describe(include='all').astype(object)

In [ ]:
tt.describe(include='bool')

In [ ]:
tt.columns

In [37]:
tt2=tt.copy()

In [39]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [41]:
tt2=tt2.rename(columns={'sex':'male/female'})

In [43]:
tt2

,survived,pclass,male/female,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [45]:
tt3=tt.copy()

In [47]:
tt3.rename(columns={'fare':'요금'}, inplace=True)

In [49]:
tt3

,survived,pclass,sex,age,sibsp,parch,요금,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [51]:
data_ex3=pd.DataFrame({
    '학년':[2,3,4,1,1,2,2,3],
    '학교':['한양대','고려대','세종대','성균관대','연세대','서울대','경북대','부산대'],
    '전공':['체육교육과','수학교육과','국어교육과','컴퓨터공학과','전자공학과','신소재공학과','철학과','경영학과']
})

In [53]:
data_ex3

   학년    학교      전공
0   2   한양대   체육교육과
1   3   고려대   수학교육과
2   4   세종대   국어교육과
3   1  성균관대  컴퓨터공학과
4   1   연세대   전자공학과
5   2   서울대  신소재공학과
6   2   경북대     철학과
7   3   부산대    경영학과

In [55]:
data_ex4=data_ex3.copy()

In [59]:
data_ex4

   학년    학교      전공
0   2   한양대   체육교육과
1   3   고려대   수학교육과
2   4   세종대   국어교육과
3   1  성균관대  컴퓨터공학과
4   1   연세대   전자공학과
5   2   서울대  신소재공학과
6   2   경북대     철학과
7   3   부산대    경영학과

In [61]:
data_ex4=data_ex4.rename(columns={'전공':'학과'})

In [63]:
data_ex4

   학년    학교      학과
0   2   한양대   체육교육과
1   3   고려대   수학교육과
2   4   세종대   국어교육과
3   1  성균관대  컴퓨터공학과
4   1   연세대   전자공학과
5   2   서울대  신소재공학과
6   2   경북대     철학과
7   3   부산대    경영학과

In [65]:
data_ex5=pd.DataFrame({
    '학교':['한양대','고려대','세종대','성균관대','연세대','서울대','경북대','부산대'],
    '학년':[2,3,4,1,1,2,2,3],
    '나이':[21,22,27,20,19,23,24,22],
})

In [67]:
data_ex5

     학교  학년  나이
0   한양대   2  21
1   고려대   3  22
2   세종대   4  27
3  성균관대   1  20
4   연세대   1  19
5   서울대   2  23
6   경북대   2  24
7   부산대   3  22

In [69]:
data_ex5['입학 나이']=data_ex5['나이']-data_ex5['학년']

In [71]:
data_ex5

     학교  학년  나이  입학 나이
0   한양대   2  21     19
1   고려대   3  22     19
2   세종대   4  27     23
3  성균관대   1  20     19
4   연세대   1  19     18
5   서울대   2  23     21
6   경북대   2  24     22
7   부산대   3  22     19

In [73]:
e=[]
for i in data_ex5['입학 나이']:
    if i<=19:
        e.append('현역/조기입학')
    else:
        e.append('N수생')

In [75]:
e

['현역/조기입학', '현역/조기입학', 'N수생', '현역/조기입학', '현역/조기입학', 'N수생', 'N수생', '현역/조기입학']

In [77]:
data_ex6=data_ex5['입학 나이']

In [79]:
data_ex6

0    19
1    19
2    23
3    19
4    18
5    21
6    22
7    19
Name: 입학 나이, dtype: int64

In [81]:
c=[]
for i in data_ex6:
    if i<=19:
        c.append('현역/조기입학')
    else:
        c.append('N수생')

In [83]:
c

['현역/조기입학', '현역/조기입학', 'N수생', '현역/조기입학', '현역/조기입학', 'N수생', 'N수생', '현역/조기입학']

In [85]:
import numpy as np

In [87]:
data_ex5

     학교  학년  나이  입학 나이
0   한양대   2  21     19
1   고려대   3  22     19
2   세종대   4  27     23
3  성균관대   1  20     19
4   연세대   1  19     18
5   서울대   2  23     21
6   경북대   2  24     22
7   부산대   3  22     19

In [89]:
data_ex5['N수생 여부']=np.where(data_ex5['입학 나이']<=19,'현역','N수생')

In [91]:
data_ex5['N수생 여부']

0     현역
1     현역
2    N수생
3     현역
4     현역
5    N수생
6    N수생
7     현역
Name: N수생 여부, dtype: object

In [93]:
data_ex5['N수생 여부'].value_counts()

N수생 여부
현역     5
N수생    3
Name: count, dtype: int64

In [95]:
data_ex5

     학교  학년  나이  입학 나이 N수생 여부
0   한양대   2  21     19     현역
1   고려대   3  22     19     현역
2   세종대   4  27     23    N수생
3  성균관대   1  20     19     현역
4   연세대   1  19     18     현역
5   서울대   2  23     21    N수생
6   경북대   2  24     22    N수생
7   부산대   3  22     19     현역

In [97]:
tt['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [99]:
tt.iloc[:10,0:4]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0
5         0       3    male   NaN
6         0       1    male  54.0
7         0       3    male   2.0
8         1       3  female  27.0
9         1       2  female  14.0

In [101]:
tt.loc[:10,['pclass','survived','age','sex']]

    pclass  survived   age     sex
0        3         0  22.0    male
1        1         1  38.0  female
2        3         1  26.0  female
3        1         1  35.0  female
4        3         0  35.0    male
5        3         0   NaN    male
6        1         0  54.0    male
7        3         0   2.0    male
8        3         1  27.0  female
9        2         1  14.0  female
10       3         1   4.0  female

In [103]:
tt.iloc[:10,[1,3]]

   pclass   age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0
5       3   NaN
6       1  54.0
7       3   2.0
8       3  27.0
9       2  14.0

In [105]:
#loc으로 하면 오류가 뜸
tt.loc[:10,[1,3]]

KeyError: "None of [Index([1, 3], dtype='int32')] are in the [columns]"

In [107]:
tt['age'].loc[5]

nan

In [109]:
tt['age'].iloc[5]

nan

In [111]:
tt['fare'].loc[888]

23.45

In [113]:
tt['fare'].iloc[888]

23.45

In [115]:
tt_1=tt.tail()

In [117]:
tt_1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [119]:
tt.loc[:10,['sex']]

       sex
0     male
1   female
2   female
3   female
4     male
5     male
6     male
7     male
8   female
9   female
10  female

In [121]:
tt.iloc[:10,['sex']]

IndexError: .iloc requires numeric indexers, got ['sex']

In [123]:
tt_1.loc[889]

survived               1
pclass                 1
sex                 male
age                 26.0
sibsp                  0
parch                  0
fare                30.0
embarked               C
class              First
who                  man
adult_male          True
deck                   C
embark_town    Cherbourg
alive                yes
alone               True
Name: 889, dtype: object

In [125]:
tt_1.iloc[890]

IndexError: single positional indexer is out-of-bounds