In [21]:
import seaborn as sns
tt=sns.load_dataset('titanic')

In [22]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [23]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [24]:
tt['sex'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: sex
Non-Null Count  Dtype
--------------  -----
891 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

In [25]:
tt['sex','age'].info()

KeyError: ('sex', 'age')

In [34]:
tt.query('age==22')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
60,0,3,male,22.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
80,0,3,male,22.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
112,0,3,male,22.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
141,1,3,female,22.0,0,0,7.7500,S,Third,woman,False,NaN,Southampton,yes,True
151,1,1,female,22.0,1,0,66.6000,S,First,woman,False,C,Southampton,yes,False
212,0,3,male,22.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
225,0,3,male,22.0,0,0,9.3500,S,Third,man,True,NaN,Southampton,no,True
243,0,3,male,22.0,0,0,7.1250,S,Third,man,True,NaN,Southampton,no,True
287,0,3,male,22.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
289,1,3,female,22.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
320,0,3,male,22.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
323,1,2,female,22.0,1,1,29.0000,S,Second,woman,False,NaN,Southampton,yes,False
356,1,1,female,22.0,0,1,55.0000,S,First,woman,False,E,Southampton,yes,False
373,0,1,male,22.0,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
376,1,3,female,22.0,0,0,7.2500,S,Third,woman,False,NaN,Southampton,yes,True
395,0,3,male,22.0,0,0,7.7958,S,Third,man,True,NaN,Southampton,no,True
474,0,3,female,22.0,0,0,9.8375,S,Third,woman,False,NaN,Southampton,no,True
478,0,3,male,22.0,0,0,7.5208,S,Third,man,True,NaN,Southampton,no,True
521,0,3,male,22.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
539,1,1,female,22.0,0,2,49.5000,C,First,woman,False,B,Cherbourg,yes,False
553,1,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,yes,True
554,1,3,female,22.0,0,0,7.7750,S,Third,woman,False,NaN,Southampton,yes,True
588,0,3,male,22.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
608,1,2,female,22.0,1,2,41.5792,C,Second,woman,False,NaN,Cherbourg,yes,False
708,1,1,female,22.0,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True

In [36]:
#no data
tt.query('fare==8')

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [38]:
tt.query("sex=='female'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [40]:
tt.query('fare >=50 or fare <= 15')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [42]:
tt.query('not fare >=50 and fare <= 90')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [44]:
tt.query("sex=='male' & survived==1")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [46]:
tt.query('''sex=='male' & survived==1''')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [48]:
tt.query("sex=='male'").query('pclass==2')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0,S,Second,man,True,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0,S,Second,man,True,D,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
70,0,2,male,32.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,0,2,male,28.0,0,1,33.0,S,Second,man,True,NaN,Southampton,no,False
861,0,2,male,21.0,1,0,11.5,S,Second,man,True,NaN,Southampton,no,False
864,0,2,male,24.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0,S,Second,man,True,NaN,Southampton,no,True

In [50]:
tt.query('''embark_town=='Southampton' or age>40 or sex=='male' and pclass==2 and fare>40 ''')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [52]:
tt.query("embark_town=='Southampton'").query('age>40').query("sex=='male'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
62,0,1,male,45.0,1,0,83.4750,S,First,man,True,C,Southampton,no,False
92,0,1,male,46.0,1,0,61.1750,S,First,man,True,E,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,0,3,male,42.0,0,0,7.5500,S,Third,man,True,NaN,Southampton,no,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
860,0,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True

In [54]:
tt.query("embark_town=='Southampton'").query('age>40').query("sex=='male'").iloc[:10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
62,0,1,male,45.0,1,0,83.4750,S,First,man,True,C,Southampton,no,False
92,0,1,male,46.0,1,0,61.1750,S,First,man,True,E,Southampton,no,False
94,0,3,male,59.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
110,0,1,male,47.0,0,0,52.0000,S,First,man,True,C,Southampton,no,True
124,0,1,male,54.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False
129,0,3,male,45.0,0,0,6.9750,S,Third,man,True,NaN,Southampton,no,True
149,0,2,male,42.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [56]:
tt[(tt['age']>40) & (tt['fare']>40)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
62,0,1,male,45.0,1,0,83.4750,S,First,man,True,C,Southampton,no,False
92,0,1,male,46.0,1,0,61.1750,S,First,man,True,E,Southampton,no,False
110,0,1,male,47.0,0,0,52.0000,S,First,man,True,C,Southampton,no,True
124,0,1,male,54.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False
155,0,1,male,51.0,0,1,61.3792,C,First,man,True,NaN,Cherbourg,no,False
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
245,0,1,male,44.0,2,0,90.0000,Q,First,man,True,C,Queenstown,no,False
262,0,1,male,52.0,1,1,79.6500,S,First,man,True,E,Southampton,no,False
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
299,1,1,female,50.0,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
337,1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
366,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False
380,1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
434,0,1,male,50.0,1,0,55.9000,S,First,man,True,E,Southampton,no,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
453,1,1,male,49.0,1,0,89.1042,C,First,man,True,C,Cherbourg,yes,False
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
496,1,1,female,54.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
513,1,1,female,54.0,1,0,59.4000,C,First,woman,False,NaN,Cherbourg,yes,False
523,1,1,female,44.0,0,1,57.9792,C,First,woman,False,B,Cherbourg,yes,False
544,0,1,male,50.0,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
571,1,1,female,53.0,2,0,51.4792,S,First,woman,False,C,Southampton,yes,False
587,1,1,male,60.0,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False
591,1,1,female,52.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
599,1,1,male,49.0,1,0,56.9292,C,First,man,True,A,Cherbourg,yes,False
621,1,1,male,42.0,1,0,52.5542,S,First,man,True,D,Southampton,yes,False
645,1,1,male,48.0,1,0,76.7292,C,First,man,True,D,Cherbourg,yes,False
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.0,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
678,0,3,female,43.0,1,6,46.9000,S,Third,woman,False,NaN,Southampton,no,False
698,0,1,male,49.0,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
712,1,1,male,48.0,1,0,52.0000,S,First,man,True,C,Southampton,yes,False
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
754,1,2,female,48.0,1,2,65.0000,S,Second,woman,False,NaN,Southampton,yes,False
765,1,1,female,51.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
779,1,1,female,43.0,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
789,0,1,male,46.0,0,0,79.2000,C,First,man,True,B,Cherbourg,no,True
820,1,1,female,52.0,1,1,93.5000,S,First,woman,False,B,Southampton,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [58]:
tt[(tt['age']>40) & (tt['embark_town']=='Southampton')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,0,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True

In [60]:
tt[(tt['age']>40) & (tt['embark_town']=='Southampton')].iloc[:10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
62,0,1,male,45.0,1,0,83.4750,S,First,man,True,C,Southampton,no,False
92,0,1,male,46.0,1,0,61.1750,S,First,man,True,E,Southampton,no,False
94,0,3,male,59.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
110,0,1,male,47.0,0,0,52.0000,S,First,man,True,C,Southampton,no,True
124,0,1,male,54.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False

In [62]:
tt[(tt['age']>40) & (tt['embark_town']=='Southampton')].loc[:30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True

In [70]:
new_tt=tt[(tt['survived']==0)& (tt['pclass']==2)][['embark_town','alive']]

In [72]:
new_tt

     embark_town alive
20   Southampton    no
33   Southampton    no
41   Southampton    no
70   Southampton    no
72   Southampton    no
..           ...   ...
854  Southampton    no
861  Southampton    no
864  Southampton    no
883  Southampton    no
886  Southampton    no

[97 rows x 2 columns]

In [122]:
new1_tt_alived=new_tt[(new_tt['alive']=='yes')]

In [124]:
#dataframe 형태

new1_tt_alived

Empty DataFrame
Columns: [embark_town, alive]
Index: []

In [126]:
new2_tt_alived=new_tt['alive']=='yes'

In [130]:
#series 형태

new2_tt_alived

20     False
33     False
41     False
70     False
72     False
       ...
854    False
861    False
864    False
883    False
886    False
Name: alive, Length: 97, dtype: bool

In [132]:
tt.sort_values('fare')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
277,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False

In [142]:
#먼저 입력한 column 기준으로 배열하는듯?

tt.sort_values(['fare','age'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False

In [140]:
tt.sort_values(['age','fare'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True

In [150]:
tt.sort_values(['age','fare'], ascending=[False,False])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True

In [156]:
sorting_tt=tt.sort_values(['age','fare']).query('age<50')

In [158]:
sorting_tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,1,1,female,49.00,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
599,1,1,male,49.00,1,0,56.9292,C,First,man,True,A,Cherbourg,yes,False
52,1,1,female,49.00,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
453,1,1,male,49.00,1,0,89.1042,C,First,man,True,C,Cherbourg,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False

In [160]:
sorting_tt1=sorting_tt.dropna()

In [162]:
sorting_tt1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,1,1,female,49.00,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
599,1,1,male,49.00,1,0,56.9292,C,First,man,True,A,Cherbourg,yes,False
52,1,1,female,49.00,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
453,1,1,male,49.00,1,0,89.1042,C,First,man,True,C,Cherbourg,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False

In [172]:
for i in sorting_tt1['embark_town']:
    if ['embark_town']=='Southampton':
        print('축구 근본 있는 지역')
    else:
        print('노근본 지역')

#southampton이 list에 있어서 결과가 나와야하는데...

노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역
노근본 지역

In [174]:
for i in sorting_tt1['age']:
    if i<=25:
        print('애기')
    else:
        print('늙은이')

애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
애기
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이
늙은이