## 필수과제들
- **필수과제1**
-  q1 - pclass 3 이고, age 20세 미만인 남성과, 여성의 카운트 수와 생존수를 비교해 주세요.
    - 코드와 데이터 값

- **필수과제2**
- 요금에 따라 3가지 등급으로 나눠주시고 (요금의 등급의 기준은 기초통계치 분위수 값으로 기준)
    - 해당 분위수에 따라 남성과 여성을 추출하고 카운팅 수, 생존수 비교해 주세요.
    
- **필수과제3**  
- 혼자온 사람과 혼자 오지 않은사람들 중에서 둘을 비교하는데
    - 공통 조건은 혼자 온 사람의 성별 여부에 따른 전체 카운팅과 생존수 비교해 주세요!
    
    
- 필수과제 요구조건
    - 쥬피터노트북, 코드와 주석, 데이터 비교값을 공유

In [3]:
import seaborn as sns

In [5]:
tt=sns.load_dataset('titanic')

In [7]:
tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
tt_alone=tt[(tt['sibsp']==0)]

In [14]:
tt_alone

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [30]:
tt_alone_male=tt_alone.query("sex == 'male'")

In [32]:
tt_alone_male

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [44]:
tt_alone_male_survived=tt_alone_male[tt_alone_male['survived']==1]

In [46]:
tt_alone_male_survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,1,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [48]:
tt_alone_male_notsurvived=tt_alone_male[tt_alone_male['survived']==0]

In [50]:
tt_alone_male_notsurvived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [34]:
tt_alone_female=tt_alone.query("sex == 'female'")

In [36]:
tt_alone_female

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [52]:
tt_alone_female_survived=tt_alone_female[tt_alone_female['survived']==1]

In [54]:
tt_alone_female_survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [56]:
tt_alone_female_notsurvived=tt_alone_female[tt_alone_female['survived']==0]

In [58]:
tt_alone_female_notsurvived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
100,0,3,female,28.0,0,0,7.8958,S,Third,woman,False,NaN,Southampton,no,True
114,0,3,female,17.0,0,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,True
140,0,3,female,NaN,0,2,15.2458,C,Third,woman,False,NaN,Cherbourg,no,False
177,0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
199,0,2,female,24.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,no,True
205,0,3,female,2.0,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
235,0,3,female,NaN,0,0,7.5500,S,Third,woman,False,NaN,Southampton,no,True
246,0,3,female,25.0,0,0,7.7750,S,Third,woman,False,NaN,Southampton,no,True
254,0,3,female,41.0,0,2,20.2125,S,Third,woman,False,NaN,Southampton,no,False
264,0,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
276,0,3,female,45.0,0,0,7.7500,S,Third,woman,False,NaN,Southampton,no,True
293,0,3,female,24.0,0,0,8.8500,S,Third,woman,False,NaN,Southampton,no,True
357,0,2,female,38.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,no,True
362,0,3,female,45.0,0,1,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
396,0,3,female,31.0,0,0,7.8542,S,Third,woman,False,NaN,Southampton,no,True
404,0,3,female,20.0,0,0,8.6625,S,Third,woman,False,NaN,Southampton,no,True
415,0,3,female,NaN,0,0,8.0500,S,Third,woman,False,NaN,Southampton,no,True
419,0,3,female,10.0,0,2,24.1500,S,Third,child,False,NaN,Southampton,no,False
474,0,3,female,22.0,0,0,9.8375,S,Third,woman,False,NaN,Southampton,no,True
501,0,3,female,21.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
502,0,3,female,NaN,0,0,7.6292,Q,Third,woman,False,NaN,Queenstown,no,True
503,0,3,female,37.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,no,True
534,0,3,female,30.0,0,0,8.6625,S,Third,woman,False,NaN,Southampton,no,True
564,0,3,female,NaN,0,0,8.0500,S,Third,woman,False,NaN,Southampton,no,True
567,0,3,female,29.0,0,4,21.0750,S,Third,woman,False,NaN,Southampton,no,False
593,0,3,female,NaN,0,2,7.7500,Q,Third,woman,False,NaN,Queenstown,no,False
638,0,3,female,41.0,0,5,39.6875,S,Third,woman,False,NaN,Southampton,no,False
654,0,3,female,18.0,0,0,6.7500,Q,Third,woman,False,NaN,Queenstown,no,True
680,0,3,female,NaN,0,0,8.1375,Q,Third,woman,False,NaN,Queenstown,no,True
702,0,3,female,18.0,0,1,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
767,0,3,female,30.5,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
772,0,2,female,57.0,0,0,10.5000,S,Second,woman,False,E,Southampton,no,True
807,0,3,female,18.0,0,0,7.7750,S,Third,woman,False,NaN,Southampton,no,True
816,0,3,female,23.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False

In [60]:
tt_alone_female_notsurvived.count()

survived       37
pclass         37
sex            37
age            29
sibsp          37
parch          37
fare           37
embarked       37
class          37
who            37
adult_male     37
deck            3
embark_town    37
alive          37
alone          37
dtype: int64

In [66]:
tt_accompanied=tt[(tt['sibsp']>=1)]

In [68]:
tt_accompanied

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [70]:
tt_accompanied_male=tt_accompanied[tt_accompanied['sex']=='male']

In [72]:
tt_accompanied_male

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,0,3,male,NaN,8,2,69.5500,S,Third,man,True,NaN,Southampton,no,False
850,0,3,male,4.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
860,0,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
861,0,2,male,21.0,1,0,11.5000,S,Second,man,True,NaN,Southampton,no,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [74]:
tt_accompanied_male_survived=tt_accompanied_male[tt_accompanied_male['survived']==1]

In [76]:
tt_accompanied_male_survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
65,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
125,1,3,male,12.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
224,1,1,male,38.00,1,0,90.0000,S,First,man,True,C,Southampton,yes,False
248,1,1,male,37.00,1,1,52.5542,S,First,man,True,D,Southampton,yes,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
267,1,3,male,25.00,1,0,7.7750,S,Third,man,True,NaN,Southampton,yes,False
301,1,3,male,NaN,2,0,23.2500,Q,Third,man,True,NaN,Queenstown,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
370,1,1,male,25.00,1,0,55.4417,C,First,man,True,E,Cherbourg,yes,False
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
453,1,1,male,49.00,1,0,89.1042,C,First,man,True,C,Cherbourg,yes,False
484,1,1,male,25.00,1,0,91.0792,C,First,man,True,B,Cherbourg,yes,False
489,1,3,male,9.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
543,1,2,male,32.00,1,0,26.0000,S,Second,man,True,NaN,Southampton,yes,False
549,1,2,male,8.00,1,1,36.7500,S,Second,child,False,NaN,Southampton,yes,False
587,1,1,male,60.00,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False
599,1,1,male,49.00,1,0,56.9292,C,First,man,True,A,Cherbourg,yes,False
621,1,1,male,42.00,1,0,52.5542,S,First,man,True,D,Southampton,yes,False
622,1,3,male,20.00,1,1,15.7417,C,Third,man,True,NaN,Cherbourg,yes,False
645,1,1,male,48.00,1,0,76.7292,C,First,man,True,D,Cherbourg,yes,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
664,1,3,male,20.00,1,0,7.9250,S,Third,man,True,NaN,Southampton,yes,False
690,1,1,male,31.00,1,0,57.0000,S,First,man,True,B,Southampton,yes,False
709,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
712,1,1,male,48.00,1,0,52.0000,S,First,man,True,C,Southampton,yes,False
724,1,1,male,27.00,1,0,53.1000,S,First,man,True,E,Southampton,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [78]:
tt_accompanied_male_survived.count()

survived       36
pclass         36
sex            36
age            33
sibsp          36
parch          36
fare           36
embarked       36
class          36
who            36
adult_male     36
deck           18
embark_town    36
alive          36
alone          36
dtype: int64

In [80]:
tt_accompanied_male_notsurvived=tt_accompanied_male[tt_accompanied_male['survived']==0]

In [82]:
tt_accompanied_male_notsurvived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,0,3,male,2.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
846,0,3,male,NaN,8,2,69.5500,S,Third,man,True,NaN,Southampton,no,False
850,0,3,male,4.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
860,0,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
861,0,2,male,21.0,1,0,11.5000,S,Second,man,True,NaN,Southampton,no,False

In [84]:
tt_accompanied_female=tt_accompanied[tt_accompanied['sex']=='female']

In [86]:
tt_accompanied_female

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [88]:
tt_accompanied_female_survived=tt_accompanied_female[tt_accompanied_female['survived']==1]

In [90]:
tt_accompanied_female_survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,1,1,female,NaN,1,0,89.1042,C,First,woman,False,C,Cherbourg,yes,False
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False

In [92]:
tt_accompanied_female_notsurvived=tt_accompanied_female[tt_accompanied_female['survived']==0]

In [94]:
tt_accompanied_female_notsurvived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
49,0,3,female,18.0,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False
71,0,3,female,16.0,5,2,46.9000,S,Third,woman,False,NaN,Southampton,no,False
111,0,3,female,14.5,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,no,False
113,0,3,female,20.0,1,0,9.8250,S,Third,woman,False,NaN,Southampton,no,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
132,0,3,female,47.0,1,0,14.5000,S,Third,woman,False,NaN,Southampton,no,False
147,0,3,female,9.0,2,2,34.3750,S,Third,child,False,NaN,Southampton,no,False
167,0,3,female,45.0,1,4,27.9000,S,Third,woman,False,NaN,Southampton,no,False
180,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
229,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
240,0,3,female,NaN,1,0,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
251,0,3,female,29.0,1,1,10.4625,S,Third,woman,False,G,Southampton,no,False
297,0,1,female,2.0,1,2,151.5500,S,First,child,False,C,Southampton,no,False
312,0,2,female,26.0,1,1,26.0000,S,Second,woman,False,NaN,Southampton,no,False
374,0,3,female,3.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
402,0,3,female,21.0,1,0,9.8250,S,Third,woman,False,NaN,Southampton,no,False
409,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
423,0,3,female,28.0,1,1,14.4000,S,Third,woman,False,NaN,Southampton,no,False
436,0,3,female,21.0,2,2,34.3750,S,Third,woman,False,NaN,Southampton,no,False
485,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
498,0,1,female,25.0,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
541,0,3,female,9.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
542,0,3,female,11.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
578,0,3,female,NaN,1,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,False
610,0,3,female,39.0,1,5,31.2750,S,Third,woman,False,NaN,Southampton,no,False
617,0,3,female,26.0,1,0,16.1000,S,Third,woman,False,NaN,Southampton,no,False
634,0,3,female,9.0,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
642,0,3,female,2.0,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
657,0,3,female,32.0,1,1,15.5000,Q,Third,woman,False,NaN,Queenstown,no,False
678,0,3,female,43.0,1,6,46.9000,S,Third,woman,False,NaN,Southampton,no,False
729,0,3,female,25.0,1,0,7.9250,S,Third,woman,False,NaN,Southampton,no,False
736,0,3,female,48.0,1,3,34.3750,S,Third,woman,False,NaN,Southampton,no,False
792,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
799,0,3,female,30.0,1,1,24.1500,S,Third,woman,False,NaN,Southampton,no,False
813,0,3,female,6.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
852,0,3,female,9.0,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
854,0,2,female,44.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,no,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [96]:
tt_accompanied_female_notsurvived.count()

survived       44
pclass         44
sex            44
age            35
sibsp          44
parch          44
fare           44
embarked       44
class          44
who            44
adult_male     44
deck            3
embark_town    44
alive          44
alone          44
dtype: int64

##결괏값
-혼자 온 사람

    남성-434명
        /생존한 남성 73명
        /생존하지 못한 남성 361명
        
    여성-174명
        /생존한 여성 137명
        /생존하지 못한 여성 37명

-같이 온 사람

    남성-143명
        /생존한 남성 36명
        /생존하지 못한 남성 107명

    여성-140명
        /생존한 여성 96명
        /생존하지 못한 여성 44명